name: Prepare Environment
on:
  workflow_dispatch:

jobs:
  prepare-env:
    runs-on: ubuntu-latest
    env:
      CF_TOKEN: ${{ secrets.CF_TOKEN }}
      CF_ZONE_ID: ${{ secrets.CF_ZONE_ID }}
      DEFAULT_CF_TOKEN: ${{ secrets.DEFAULT_CF_TOKEN }}
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
